version: '3'
services:
  rd:
    build: ./src
    container_name: rd
    ports:
     - "4000:80"
    volumes:
     - ./src:/app
    restart: always
  db:
    build: ./db
    container_name: db
    ports:
      - "4001:5432"
    restart: always
    volumes:
      - "./db:/db"